name: CI/CD Pipeline
on:
  push:
    branches:
      - main
      - production
      - development

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [production, development]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker Image
      run: |
        docker build -t devopsnazim/my-app:${{ matrix.environment }} .
        docker push devopsnazim/my-app:${{ matrix.environment }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        environment: [production, development]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set EC2 IP Address and Deploy to AWS EC2
      run: |
        # Set the EC2 IP address based on the environment
        if [ "${{ matrix.environment }}" == "production" ]; then
          EC2_IP=${{ secrets.AWS_EC2_IP_PRODUCTION }}
        else
          EC2_IP=${{ secrets.AWS_EC2_IP_DEVELOPMENT }}
        fi

        # SSH into EC2 and deploy the app
        ssh -o StrictHostKeyChecking=no -i ${{ secrets.AWS_SSH_KEY }} ubuntu@$EC2_IP << EOF
        cd /home/ubuntu/my-app
        ./deploy.sh
        EOF

