name: CI/CD Pipeline
on:
  push:
    branches:
      - main
      - development

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [production, development]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_region: us-east-1  # Make sure to use your AWS region

    - name: Log in to Amazon ECR
      uses: docker/login-action@v2
      with:
        ecr: true
        region: us-east-1  # Make sure to use your AWS region

    - name: Build and Push Docker Image to ECR
      run: |
        # Log in to ECR (optional if using docker/login-action)
        aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ secrets.AWS_ECR_REGISTRY }}

        # Build and tag your image
        docker build -t ${{ secrets.AWS_ECR_REGISTRY }}/my-app:${{ matrix.environment }} .

        # Push to ECR
        docker push ${{ secrets.AWS_ECR_REGISTRY }}/my-app:${{ matrix.environment }}

