name: CI/CD Pipeline
on:
  push:
    branches:
      - main
      - development

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [production, development]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker Image
      run: |
        docker build -t devopsnazim/my-app:${{ matrix.environment }} .
        docker push devopsnazim/my-app:${{ matrix.environment }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        environment: [production, development]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Deploy to AWS EC2
      run: |
        ssh -o StrictHostKeyChecking=no -i ${{ secrets.AWS_SSH_KEY }} ubuntu@${{ secrets['AWS_EC2_IP_' + matrix.environment | upper] }} << EOF
        cd /home/ubuntu/my-app
        ./deploy.sh
        EOF
      env:
        AWS_EC2_IP_PRODUCTION: ${{ secrets.AWS_EC2_IP_PRODUCTION }}
        AWS_EC2_IP_DEVELOPMENT: ${{ secrets.AWS_EC2_IP_DEVELOPMENT }}

